export const metadata = {
  title: {
    absolute: "",
    default: "Next.js Tutorial - About Attempt Seven",
    template: "%s | About Attempt Seven"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem"
          }}>
          <p>Header</p>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem"
          }}>
          <p>Footer</p>
        </footer>
        </body>
    </html>
  )
}
