export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function ProductsLayout({ children }) {
  return (
    <>
      {children}
      <h2>Features products</h2>
    </>
  )
}
